server:
  port: ${SERVICE_SERVER_PORT:8080}

spring:
  application:
    name: ${SERVICE_APPLICATION_NAME:notification-service}
  profiles:
    active: ${SPRING_PROFILE:default}

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true
      transport:
        protocol: smtp


  elasticsearch:
    uris: ${ELASTICSEARCH_URI:your_elasticsearch_url}
    username: ${ELASTICSEARCH_USERNAME:your_elasticsearch_username}
    password: ${ELASTICSEARCH_PASSWORD:your_elasticsearch_password}
  data:
    mongodb:
      uri: ${MONGO_URI:your_mongodb_uri}
  kafka:
    bootstrap-servers: ${KAFKA_URI:your_kafka_bootstrap_servers}
    properties:
      security.protocol: SASL_SSL
      sasl.jaas.config: org.apache.kafka.common.security.plain.PlainLoginModule required username='${CLUSTER_API_KEY}' password='${CLUSTER_API_SECRET}';
      sasl.mechanism: PLAIN
      session:
        timeout.ms: 45000
      spring.json.type.mapping: notification:com.onlineshop.notificationservice.kafka.consumer.NotificationConsumer
      group-id: ${SERVICE_APPLICATION_NAME:notification-service}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      group-id: ${SERVICE_APPLICATION_NAME:notification-service}

    wishlist-notification-added-product-topic: ${WHISHLIST_NOTIFICATION_ADDED_TOPIC:online-shop-wishlist-notification-added-product}

management:
  endpoints:
    web:
      exposure:
        include: ${ENDPOINTS_INCLUDE:*}
  endpoint:
    health:
      show-details: ${HEALTH_SHOW_DETAILS:always}

swagger:
  documentation:
    uri: ${SWAGGER_URI:http://localhost:8080/swagger-ui/index.html}


springdoc:
  packages-to-scan: com.runapp.notificationservice
